version: "3.2"

services:

  checkout_backend_mock:
    image: checkout_backend_mock_image:v1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/usr/src/app
